# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'myControllers' do
	pod 'SnapKit', '~> 0.20'
	pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Curry'
    pod 'Argo'
    pod 'Alamofire'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    pod 'Firebase'
end
